version: '3.7'
services:
  database:
    image: mariadb:latest
    restart: unless-stopped
    container_name: database
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: agence_voyage
      MYSQL_USER: agence
      MYSQL_PASSWORD: toor
      MYSQL_ROOT_PASSWORD: toor
    volumes:
      - ./storage-db:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app_network

  #Phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8585:80"
    container_name: phpmyadmin
    depends_on:
      - database
    environment:
      PMA_HOST: database
    networks:
      - app_network

# Docker Networks
networks:
  app_network:
    driver: bridge